# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestPractical' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'ReactorKit'
  pod 'Then'
  pod 'RxDataSources', '~> 3.0'
  pod 'RxOptional'
   pod 'SnapKit', '~> 4.0.0'
  # Pods for UnitTestPractical

  target 'UnitTestPracticalTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'RxExpect'
  end

  target 'UnitTestPracticalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
