# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeroExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 4.0.0'
pod 'Hero'
  # Pods for HeroExample

  target 'HeroExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HeroExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
